### ISSUE TITLE
Asynchronous listen_to_queue

### ISSUE THREAD

**Issue by OAGr** [iHiD/propono#64]
I appreciate asynchronous publishing, but that makes subscribing a bottleneck.  I seem to reach subscribing speeds of around 0.6-1 message/second using the `Propono.listen_to_queue` method with one thread.

I later tested this with multiple threads and that does speed it up.  It would be convenient if this were built into Propono.  I imagine that long polling in v2 should help with this.  

```
  def async_subscribe(i)
    i.times.each do |ii|
      puts "created thread #{ii}"
      @threads << Thread.new(messages) { subscribe }
    end
    @threads.join
  end

  def subscribe
    Propono.listen_to_queue(:foobar) do |message|
      puts message
    end
  end
```

**Comment by iHiD** [comment]
IIRC Propono gets about 10 messages at once to work through, so you shouldn't be seeing that big a gap if you have lots of messages. For end-to-end though, I can 1s being the timeframe. Actually publishing to / seeing messages on SQS takes a while (probably the SNS -> SQS jump) so that might be part of the issue. Totally agree that long polling in v2 should minimise this to the max (so to speak!)

I just need a free weekend to finish it!

Thanks for your comments and questions. :blue_heart:

**Comment by onomated** [comment]
+1
